FINANCE_CARD_CATALOG = [
    {
        "id": "balance",
        "title": "Saldo",
        "size": "2x1",
        "icon": "💰",
        "group": "module",
    },
    {
        "id": "account_balance",
        "title": "Conta Bancária",
        "size": "2x1",
        "icon": "🏦",
        "group": "module",
    },
    {
        "id": "credit_card",
        "title": "Cartão de Crédito",
        "size": "1x1",
        "icon": "💳",
        "group": "module",
    },
    {
        "id": "fixed_expenses_sheet",
        "title": "Gastos Fixos",
        "size": "1x3",
        "icon": "📋",
        "group": "module",
    },
    {
        "id": "pix_sheet",
        "title": "Pix do Mês",
        "size": "1x3",
        "icon": "💸",
        "group": "module",
    },
    {
        "id": "subscriptions",
        "title": "Assinaturas",
        "size": "1x1",
        "icon": "🔁",
        "group": "module",
    },
    {
        "id": "expenses_chart",
        "title": "Gráfico de Gastos",
        "size": "3x3",
        "icon": "📊",
        "group": "module",
    },
    {
        "id": "calculator",
        "title": "Calculadora",
        "size": "1x1",
        "icon": "🧮",
        "group": "tool",
    },
]